server:
  port: 8899
spring:
  data:
    mongodb:
      host:
      uri: mongodb://118.31.20.148:27017/storage
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://118.31.20.148:3306/juhai?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true
mybatis:
  mapper-locations: classpath:mapper/*.xml
